config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :pages
  resources :articles
  get "signup", to: "users#new"

  resources :users, except: [:new] do
    resources :follows, only: [:create, :destroy]
  end

  get '/:user_id/followers', to: 'follows#follower_users', as: 'follower_users'
  get '/:user_id/followings', to: 'follows#following_users', as: 'followings_users'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

  resources :add, only: [:new, :create]
  # post '/follows', to: 'follows#create', as: 'follow'
  # delete '/follows', to: 'follows#destroy', as: 'delete_follow'
  #resources :follows, only: [:create, :destroy]
  post 'add/new', to: 'add#create'
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 6, maximum: 100} 
    validates :description, presence: true, length: {minimum: 10, maximum: 100}
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def show
    end

    def new
        @article = Article.new
    end
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was edited successfully."
            redirect_to @article
        else
            render :edit
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end
    
    private
        def set_article
            @article = Article.find(params[:id])
        end

        def article_params
            params.require(:article).permit(:title, :description, category_ids: [])
        end

        def require_same_user
            if current_user != @article.user && !current_user.admin?
                flash[:alert] = "You can only edit or delete your own articles"
                redirect_to @article
            end
        end
end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                        <% if article.user %>
                            Created by <%= link_to article.user.username, user_path(article.user) %>
                        <%end %>

                        <% if article.categories.any? %>
                            <div class="mt-2"><%= render article.categories %></div>
                        <%end%>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
                        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                        <%= link_to "View", article_path(article), class: "btn btn-outline-success"%>
                        <% if logged_in? && (article.user == current_user || current_user.admin?)%>
                            <%= link_to "Edit", edit_article_path(article.id), class: "btn btn-outline-info"%>
                            <%= link_to "Destroy", article_path(article),
                                            method: :delete,
                                            data: {confirm: "Are you sure?"},
                                            class: "btn btn-outline-danger" %>
                        <%end%>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(article.created_at) %> ago,
                        edited <%= time_ago_in_words(article.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div> 
    <%end%>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @article %>
            <%= form_with model: article, class: "shadow p-3 mb-3 bg-info rounded" do |form| %>
                <div class="form-group row">
                    <%= form.label :title, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= form.label :description, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= form.text_area :description, rows:10, class: "form-control shadow rounded", placeholder: "Description of article"%>
                    </div>
                </div>

                <div class="form-group row">
                    <%= form.label :category, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= form.collection_select(:category_ids, Category.all, :id, :name,
                                                    { prompt: "Please Select Categories"}, {multiple: true, size: 4, class: "custom-select shadow rounded"}) %>
                    </div>
                </div>

                <div class="form-group row justify-content-center">
                    <%= form.submit class: "btn btn-outline-light btn-lg" %>
                </div>
            <% end %>
        </div>
        <div class="mb-3">
            <%= link_to "[ Cancel and return to Article Listing ]", articles_path, class: "text-info" %>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4"> Edit article </h1>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4"> Tweets </h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
    <%= render 'article' %>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4"> Create new article </h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"> <%= @article.title %></h2>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="card-header font-italic">
                <% if @article.user %>
                    Created by <%= link_to @article.user.username, user_path(@article.user) %>
                <%end %>
                <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                <% if @article.categories.any? %>
                    <div class="mt-2"><%= render @article.categories %></div>
                <%end%>

                </div>
            <div class="card-body">
                <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                    <%= link_to "Edit", edit_article_path(@article.id), class: "btn btn-outline-info"%>
                    <%= link_to "Destroy", article_path(@article),
                                    method: :delete,
                                    data: {confirm: "Are you sure?"},
                                    class: "btn btn-outline-danger" %>
                <%end%>
            </div>
            <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
                edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
            </div>
        </div>
    </div>
</div> 