config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :pages
  resources :articles
  get "signup", to: "users#new"

  resources :users, except: [:new] do
    resources :follows, only: [:create, :destroy]
  end

  get '/:user_id/followers', to: 'follows#follower_users', as: 'follower_users'
  get '/:user_id/followings', to: 'follows#following_users', as: 'followings_users'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

  resources :add, only: [:new, :create]
  # post '/follows', to: 'follows#create', as: 'follow'
  # delete '/follows', to: 'follows#destroy', as: 'delete_follow'
  #resources :follows, only: [:create, :destroy]
  post 'add/new', to: 'add#create'
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy

    has_many :follows, dependent: :destroy

    has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
    has_many :followers, through: :follower_relationships, source: :follower

    has_many :following_relationships, foreign_key: :user_id, class_name: 'Follow'
    has_many :following, through: :following_relationships, source: :following

    validates :username, presence: true,
                        uniqueness: { case_sensitive: false },
                        length: {minimum: 3,  maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: {maximum: 105},
                    format: { with: VALID_EMAIL_REGEX}

    has_secure_password

    self.per_page = 5
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :new, :create]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @users = User.paginate(page: params[:page])
    end
    
    def show  
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "User #{@user.username} was created successfully."
            redirect_to @user
        else
            render :new
        end
    end

    def edit   
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "User #{@user.username} was update successfully."
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles successfully deleted."
        redirect_to articles_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You only can edit your own profile"
            redirect_to @user
        end
    end
end

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @user %>
            <%= form_with model: user, class: "shadow p-3 mb-3 bg-info rounded" do |form| %>
                <div class="form-group row">
                    <%= form.label :username, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= form.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a Username" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= form.label :email, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= form.email_field :email, class: "form-control shadow rounded", placeholder: "Enter the email" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= form.label :password, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= form.password_field :password, class: "form-control shadow rounded", placeholder: "Select a Password"%>
                    </div>
                </div>
                <div class="form-group row justify-content-center">
                    <%= form.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
                </div>
            <% end %>
        </div>
        <div class="mb-3">
            <%= link_to "[ Cancel and return to Main Page ]", root_path, class: "text-info" %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4"> Edit user for Blog </h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> Users </h1>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>
<div class="container">
    <% @users.each do |user| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                            <%= link_to user.username, user_path(user) %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"> <%= link_to gravatar_for(user, size: 150), user %> </h5>
                        <p class="card-text"><%= pluralize(user.articles.count, "Tweets") %></p>
                        <%= link_to "View Profile", user_path(user), class: "btn btn-outline-success"%>
                        <% if logged_in? %>
                            <% if current_user == user%>
                                <%= link_to "Edit Profile", edit_user_path(user.id), class: "btn btn-outline-info"%>
                            <%end%>
                            <% if current_user.admin? %>
                                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: "delete", data: {confirm: "Are you sure you wan to delete the user account and all associated articles?"}%>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>Joined <%= time_ago_in_words(user.created_at) %> ago,
                        Updated <%= time_ago_in_words(user.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div> 
    <%end%>
</div>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"> Sign Up for Blog </h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> <%= @user.username%>'s Profile </h1>

<%= gravatar_for @user, size: 200 %>
<% if logged_in? && current_user == @user%>
    <div class="text-center mt-4"><%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-outline-info"%></div> 
<% end %>

<% unless current_user.id == @user.id %>
    <% if current_user.following.exists?(@user.id)%>
        <div class="text-center mt-4"><%= link_to 'Unfollow', user_follow_path(@user), method: :delete, class: 'btn btn-outline-danger' %></div>
    <% else %>
        <div class="text-center mt-4"><%= link_to 'Follow', user_follows_path(@user), method: :create, class: 'btn btn-outline-success'  %></div>
    <% end %>
<% end %>

<table class="table table-sm">
    <thead>
        <tr>
            <th style="text-align: center;">Tweets</th>
            <th style="text-align: center;"><%= link_to 'Followers', follower_users_path(@user) %></th>
            <th style="text-align: center;"><%= link_to 'Following', followings_users_path(@user) %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="text-align: center;"><%= @user.articles.size %></td>
            <td style="text-align: center;"><%= @user.followers.size %></td>
            <td style="text-align: center;"><%= @user.following.size %></td>
        </tr>
    </tbody>
</table>

<h3 class="text-center mt-4"> Tweets </h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article'%>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>