config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :pages
  resources :articles
  get "signup", to: "users#new"

  resources :users, except: [:new] do
    resources :follows, only: [:create, :destroy]
  end

  get '/:user_id/followers', to: 'follows#follower_users', as: 'follower_users'
  get '/:user_id/followings', to: 'follows#following_users', as: 'followings_users'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

  resources :add, only: [:new, :create]
  # post '/follows', to: 'follows#create', as: 'follow'
  # delete '/follows', to: 'follows#destroy', as: 'delete_follow'
  #resources :follows, only: [:create, :destroy]
  post 'add/new', to: 'add#create'
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
        <small>Owner &copy; <%= link_to "GitHub", "https://github.com/JCansta/Twitter-Clone", class: "text-white" %></small>
    </div>
    <div class="container text-center">
        <small><%= link_to "LinkedIN", "https://www.linkedin.com/in/jaime-castro-96a1791b0", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Twitter Clone", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= link_to "Users", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Tweets
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <% if logged_in? %>
                        <%= link_to "Create new Tweet", new_article_path, class: "dropdown-item" %>
                    <% end %>
                    <%= link_to "Tweets", articles_path, class: "dropdown-item" %>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "View categories", categories_path, class: "dropdown-item" %>
                    <% if logged_in? && current_user.admin?%>
                        <%= link_to "Create new Category", new_category_path, class: "dropdown-item" %>
                    <% end %>
                </div>
            </li>

            <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "My Profile", current_user, class: "dropdown-item" %>
                    <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item"%>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Logout", logout_path, class: "dropdown-item", method: :delete%>
                    <%= link_to "Delete Profile", user_path(current_user ), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" }%>
                    <% if logged_in? && current_user.admin?%>
                        <%= link_to "Upload Excel Users", add_new_path , class: "dropdown-item text-info" %>
                    <% end %>
                </div>
            </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Log In", login_path, class: "nav-link"%>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign Up", signup_path, class: "nav-link"%>
                </li>
            <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter Clone</title>
    <link rel="icon" href="app/assets/images/Twitter_logo_blue.png" type="image/x-icon">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>